// 库中内置方法

const gcsBiz = {
  'put&/api/active_gps/{device}': 'updateDevice',
  'get&/api/active_gps': 'getActiveGps',
  'get&/api/active_gps/{device}/latest': 'getActiveGpsByDevice',
  'get&/api/active_gps/devices/latest': 'getActiveGpsDevicesLatest',
  'get&/api/history_gps/{device}/latest': 'getHistoryGpsDeviceLatest',
  'get&/api/history_gps/{device}': 'getHistoryGpsByDevice',
  'get&/api/history_gps': 'getHistoryGps',
  'put&/api/history_gps': 'updateHistoryGps',
  'get&/api/history_gps/devices': 'getDevicesHistory',
};

const cgsBiz = {
  'post&/api/UniformSpeech': 'textToSpeech',
  'get&/api/UniformSpeech/voicenames': 'getVoiceNames',
  'get&/api/UniformSpeech/voiceinfos': 'getVoiceInfos',
};

const mmtBiz = {
  'get&/api/MultimediaTransfers': 'getMultimediaTransfers',
  'get&/api/MultimediaTransfers/{id}': 'getMultimediaTransfersById',
  'delete&/api/MultimediaTransfers/{id}': 'deleteMultimediaTransfers',
  'get&/api/Templates/{id}': 'getTemplatesById',
  'get&/api/Templates': 'getTemplates',
  // 22-10-28
  'post&/api/MultimediaTransfers': 'addMultimediaTransfers',
  'post&/api/Templates': 'addTemplates',
  'put&/api/Templates/{id}': 'editTemplates',
  'delete&/api/Templates/{id}': 'deleteTemplates',
  'post&/api/MultimediaTransfers/search':'searchMultimediaTransfers',
};

const aggsBiz = {
  'get&/api/events/{eventId}/multimediatransfers': 'getMultimediaTransfersByEventId',
  'get&/api/events/{eventId}/multimediatransfers/{id}': 'getMultimediaTransfersById',
  'get&/api/Camera/groups': 'getAllCameraGroups',
  'get&/api/DetectionTasks': 'getDetectionTasks',
  'get&/api/DetectionTasks/{id}': 'getDetectionTaskById',
  'get&/api/Events': 'getEvents',
  'get&/api/Events/{id}': 'getEventInfo',
  'get&/api/Events/running': 'getRunningEvents',
  'get&/api/Events/history': 'getEventsHistory',
  'get&/api/GpsSearch': 'getGps',
  'get&/api/Layers/statistics/root_layers': 'getLayerStatisticsTotal',
  'get&/api/Layers/statistics/batch_layers': 'getRootLayerStatisticsTotal',
  'get&/api/Tasks/AssociateData': 'getTaskAssociateData',
  'get&/api/Events/AssociateData': 'getEventsAssociateData',
  'post&/api/Alarms/GetAlarmInfo': 'getAlarmInfo',
  'get&/api/Alarms/GetAlarmsByDistrictIds': 'getAlarmsByDistrictIds',
  'post&/api/Facilities/condition_query': 'queryFacilities',
  'get&/api/events/{eventId}/files': 'getFilesByEventId',
  'get&/api/events/{eventId}/files/{id}': 'getFilesById',
  'get&/api/Tasks/{id}': 'getTasksById',
  'get&/api/event/{eventId}/Tasks': 'getTasksByEventId',
  'get&/api/Tasks': 'queryTasks',
  'get&/api/Tasks/{id}/children': 'getChildrenTasksById',
  'get&/api/GbLowerDomains': 'getGbLowerDomains',
  'get&/api/Statistical/events': 'getEventCount',
  'get&/api/Events/base': 'getBaseEvents',
  'get&/api/Statistical/resources': 'getResourceCount',
  // 2022-10-25
  'get&/api/events/{eventId}/communications': 'getCommunicationByEventId',
  'get&/api/events/{eventId}/communications/{id}': 'getCommunicationById',
  'post&/api/Goods/search': 'searchGoods',
  'get&/api/Roles/{role}/members': 'getMembersByRole',
  'get&/api/Roles/{role}/organizations': 'getOrganizationsByRole',
  'get&/api/Roles/{role}/districts': 'getDistrictsByRole',
  'get&/api/Roles/{role}/camera/groups': 'getCameraGroupsByRole',
  // 2022-10-28
  'get&/api/Preplans/{id}/group': 'searchPreplanGroups',
  // 22-12-20
  'get&/api/Events/{id}/Members': 'getEventsMembers',
  //23-01-03
  'get&/api/Files': 'getFiles',
  //23-02-15
  'get&/api/GbLowerDomains/{id}': 'getGbLowerDomainsById',
  'get&/api/Preplans/{eventId}/match': 'getPreplansByEventId',
  // 23-03-14
  'post&/api/GbLowerDomains': 'addGbLowerDomains',
  'delete&/api/GbLowerDomains/{id}': 'deleteGbLowerDomains',
  'put&/api/GbLowerDomains/{id}': 'editGbLowerDomains',
  // 23-03-21
  'get&/api/Groups/{id}/members': 'getGroupMember',
  // 23-03-23
  'post&/api/ResourceRelationships/resource': 'getMainResource',
  'post&/api/ResourceRelationships/resource/single': 'getSingleResource',
  'post&/api/ResourceRelationships/resource/search': 'searchResource',
  // 23-4-4
  'post&/api/Events': 'searchEvents',
  'post&/api/Facilities/event/{eventId}': 'searchFacilitiesByEventId',
  'post&/api/Facilities/event/{eventId}/statistics': 'searchFacilityTotalByEventId',
  'post&/api/Groups': 'getGroups',
  'post&/api/Groups/search': 'searchGroups',
  'get&/api/Topologys': 'getTopology',
  // 23-4-7
  'post&/api/Platforms': 'getPlatforms',
  'post&/api/Statistical/Area/Terminal': 'getTerminalByArea',
  'post&/api/Statistical/Area/Platform': 'getPlatformByArea',
  //23-4-17
  'get&/api/Assets/{id}': 'getAssetsById',
  'post&/api/Assets': 'searchAssets',
  //23-4-20
  'post&/api/Camera': 'searchCameras',
  //23-5-4
  'post&/api/Terminals': 'searchTerminals',
  // 23-6-27
  'post&/api/AlertRecords/search': 'searchAlertRecord',
  'post&/api/Districts/{userId}': 'judgeAreaCodePermission',
  'post&/api/Preplans': 'searchPreplans',
  'post&/api/ResourceRelationships/eventTypeGroup': 'bindEventTypeGroup',
  'post&/api/Statistical/overview/asset': 'getAssetOverview',
  'post&/api/Statistical/overview/client': 'getClientOverview',
  'post&/api/Statistical/overview/terminal': 'getTerminalOverview',
  // 23-7-10
  'post&/api/ResourceRelationships/alarmType': 'bindAlarmType',
  // 23-7-17
  'post&/api/AlertRecords/converter/event': 'alarmToEvent',
  'put&/api/Roles/{role}/participators/batch': 'batchAddRole',
  // 23-8-1
  'get&/api/Projects/{id}/export': 'exportProject',
  'post&/api/Projects/import': 'importProject',
  // 23-8-11
  'get&/api/Projects/{id}': 'getProjectById',
  'get&/api/GpsSearch/active/{device}/latest': 'getDeviceGps',
  'post&/api/GpsSearch/active/devices/latest': 'searchDevicesGps',
  'get&/api/GpsSearch/history/{device}': 'getDeviceGpsHistory',
  'get&/api/GpsSearch/history/{device}/latest': 'getDeviceLatestGps',
  'post&/api/Preplans/grouping': 'searchPreplanGroup',
  'post&/api/StreamKeepAliveJobs': 'addStreamKeepAliveJobs',
  'get&/api/StreamKeepAliveJobs': 'getStreamKeepAliveJobs',
  'get&/api/StreamKeepAliveJobs/{id}': 'getStreamKeepAliveJobById',
  'put&/api/StreamKeepAliveJobs/{id}': 'editStreamKeepAliveJob',
  'delete&/api/StreamKeepAliveJobs/{id}': 'deleteStreamKeepAliveJob',
  'get&/api/Districts/Coordinate': 'getDistrictByCoordinate',
  'post&/api/Terminals/Camera': 'searchCameraTerminals',
  'post&/api/Assets/circle_area': 'getNearAssets',
  'post&/api/Assets/circle_area/Alert': 'getNearAlerts',
  'post&/api/Camera/circle_area': 'getNearCameras',
  'post&/api/Facilities/circle_area': 'getNearFacilities',
  'post&/api/Statistical/facilities/circle_area/mergence': 'getSurroundFacilitiesTotal',
  'get&/api/search/resource': 'queryResource',
  'post&/api/Camera/custom':'addCameraTerminal',
  'put&/api/Camera/custom/{id}':'editCameraTerminal',
  'post&/api/Projects':'addProject',
  'get&/api/events/{eventId}/pictures':'getEventPictures',
  'get&/api/events/{eventId}/pictures/{id}':'getEventPictureById',
  'get&/api/events/{eventId}/videos':'getEventVideos',
  'get&/api/events/{eventId}/videos/{id}':'getEventVideoById',
  'post&/api/Statistical/Layers/resource':'getLayerResourceTotal',
  'get&/api/MultimediaTransfers/{id}':'getMultimediaTransferDetails',
  'post&/api/MultimediaTransfers':'searchMultimediaTransfers',
};

const authBiz = {
  'get&/api/clients': 'getClients',
  'get&/api/clients/{client}': 'getClientInfo',
  'get&/api/permissionDatas/{data}/roles': 'getRolesByPermission',
  'get&/api/permissionDatas': 'getPermissionDataByPath',
  'get&/api/roles/permissionDatas': 'getPermissionData',
  'get&/api/roles/{role}/permissionDatas': 'getPermissionDataByRole',
  'post&/api/roles/{role}/permissionDatas': 'addPermissionDataToRole',
  'delete&/api/roles/{role}/permissionDatas': 'deletePermissionDataRole',
  'delete&/api/roles/{role}/allPermissionDatas': 'deleteAllPermissionData',
  'post&/api/roles/{role}/batchPermissionDatas': 'batchAddPermissionDataToRole',
  'put&/api/roles/{role}/batchPermissionDatas': 'batchUpdatePermissionDataToRole',
  'get&/api/users/{user}/permissionDatas': 'getPermissionDataByUser',
  'get&/api/functions/root': 'getRootFunctions',
  'get&/api/functions': 'getFunctions',
  'post&/api/functions': 'addFunctions',
  'get&/api/functions/{pid}/paging': 'getFunctionsByPid',
  'get&/api/functions/{id}': 'getFunctionsById',
  'put&/api/functions/{id}': 'updateFunctions',
  'delete&/api/functions/{id}': 'deleteFunctions',
  'post&/api/roles/{role}/participators': 'addUserToRole',
  'get&/api/roles/{role}/participators': 'getRoleUsers',
  'post&/api/roles/{role}/batchParticipators': 'addUsersToRole',
  'put&/api/roles/{role}/batchParticipators': 'changeRoleUsers',
  'delete&/api/roles/{role}/batchParticipators': 'deleteRoleUsers',
  'delete&/api/roles/{role}/participators/{user}': 'deleteRoleUser',
  'get&/api/users/{user}/participating': 'getRolesByUser',
  'get&/api/user/participating': 'getUserRoles',
  'get&/api/roles/{role}/visiting': 'getPermissionByRole',
  'post&/api/roles/{role}/visiting': 'addPermissionToRole',
  'post&/api/roles/{role}/BatchVisiting': 'addPermissionToRoles',
  'put&/api/roles/{role}/BatchVisiting': 'updateRolePermissions',
  'delete&/api/roles/{role}/visiting/{client}': 'deleteRolePermission',
  'get&/api/users/{user}/visiting': 'getUserPermissions',
  'get&/api/user/visiting': 'getPermissions',
  'get&/api/roles': 'getRoles',
  'post&/api/roles': 'addRoles',
  'get&/api/roles/{id}': 'addRolesById',
  'put&/api/roles/{id}': 'updateRoles',
  'delete&/api/roles/{id}': 'deleteRoles',
  'delete&/api/roles/{role}/permissionDatas/functionModule': 'unbindPermissionData',
  'post&/api/roles/{role}/permissionDatas/functionModule': 'bindPermissionData',
  // 22-10-28
  'delete&/api/roles/{role}/batchPermissionDatas': 'deletePermissionDatas',
  'delete&/api/roles/{role}/permissionDatas/functionModule/all': 'unbindAllPermissionData',
  'put&/api/users/{user}/batchParticipators': 'batchChangeRoleUsers',
  //23-4-4
  'post&/api/clients/config': 'addClient',
  'get&/api/clients/config': 'getClientConfig',
  'put&/api/clients/config/{clientId}': 'editClientConfig',
  'delete&/api/clients/config/{clientId}': 'deleteClientConfig',
  'get&/api/clients/config/{clientId}': 'getClientConfigById',
};

const edmsBiz = {
  'get&/api/TextTemplates': 'getTextTemplates',
  'put&/api/ClientContext/kick_out/{type}': 'kickOutUser',
  'put&/api/NightServices/duty': 'phoneDuty',
  'put&/api/NightServices/auto': 'autoVoice',
  'put&/api/NightServices/close': 'closeNightServices',
  'get&/api/NightServices/user': 'getUserNightServicesState',
  'get&/api/NightServices': 'getNightServicesStatus',
  'get&/api/Faxes': 'getFaxList',
  'post&/api/Faxes': 'sendFax',
  'get&/api/Faxes/{id}': 'getFaxInfoById',
  'put&/api/Faxes/{id}/resend': 'resendFax',
  'get&/api/Faxes/draft': 'getDraftFaxList',
  'get&/api/Faxes/draft/{id}': 'getDraftFaxInfoById',
  'delete&/api/Faxes/draft/{id}': 'deleteDraftFax',
  'put&/api/Faxes/draft/{id}/send': 'sendDraftFax',
  'put&/api/Faxes/{id}/abandon': 'moveFaxToRecycleBin',
  'delete&/api/Faxes/{id}/forever': 'deleteRecycleBinFax',
  'put&/api/Faxes/{id}/recover': 'recoverRecycleBinFax',
  'put&/api/Faxes/{id}/read': 'readFax',
  'get&/api/VirtualNCDevices': 'getVirtualNCDevices',
  'post&/api/VirtualNCDevices': 'addVirtualNCDevices',
  'get&/api/VirtualNCDevices/{id}': 'getVirtualNCDevicesById',
  'put&/api/VirtualNCDevices/{id}': 'editVirtualNCDevices',
  'delete&/api/VirtualNCDevices/{id}': 'deleteVirtualNCDevices',
  'get&/api/VirtualNCDevices/{id}/trunk_group_configs': 'getVncTrunkGroupConfigs',
  'put&/api/VirtualNCDevices/{id}/trunk_group_configs': 'editVncTrunkGroupConfigs',
  'put&/api/VirtualNCDevices/{id}/trunk_group_configs/refresh': 'refreshVncTrunkGroupConfigs',
  'put&/api/VirtualNCDevices/{id}/phones/refresh': 'refreshVncPhones',
  'get&/api/VirtualNCDevices/{id}/phones': 'getVncPhones',

  'post&/api/Appointments/conference': 'addAppointmentsConference',
  'get&/api/Appointments/conference': 'getAppointmentsConference',
  'get&/api/Appointments/conference/{id}': 'getAppointmentsConferenceById',
  'put&/api/Appointments/conference/{id}': 'editAppointmentsConference',
  'delete&/api/Appointments/conference/{id}': 'deleteAppointmentsConference',
  'post&/api/Appointments/voice_notify': 'addAppointmentsVoiceNotify',
  'get&/api/Appointments/voice_notify/{id}': 'getAppointmentsVoiceNotifyById',
  'put&/api/Appointments/voice_notify/{id}': 'editAppointmentsVoiceNotify',
  'delete&/api/Appointments/voice_notify/{id}': 'deleteAppointmentsVoiceNotify',
  'put&/api/Appointments/voice_notify/{id}': 'editSingleAppointmentsVoiceNotify',
  'put&/api/CallBiz': 'callBiz',
  'get&/api/ClientContext': 'getClientContext',
  // 'post&/api/ConferenceBiz/conference': 'addConference',
  // 'get&/api/ConferenceBiz/conference': 'getConference',
  // 'delete&/api/ConferenceBiz/conference/{id}': 'closeConference',
  // 'get&/api/ConferenceBiz/conference/{id}/member': 'getConferenceMember',
  // 'post&/api/ConferenceBiz/broadcast_group/{userID}': 'addBroadcastGroup',
  // 'get&/api/ConferenceBiz/broadcast_group': 'getBroadcastGroup',
  // 'get&/api/ConferenceBiz/broadcast_group/{id}/members': 'getBroadcastGroupMembers',
  // 'delete&/api/ConferenceBiz/broadcast_group/{id}': 'closeBroadcastGroup',
  'get&/api/DataRequestBiz/phonelines': 'getPhoneLines',
  'get&/api/DataRequestBiz/conference_record': 'getConferenceRecord',
  'get&/api/DataRequestBiz/conference_record/{id}': 'getConferenceRecordById',
  'get&/api/DataRequestBiz/call_record': 'getCallRecord',
  'put&/api/DataRequestBiz/call_record/call_video_id': 'addVideoIdForCallRecord',
  'get&/api/DataRequestBiz/call_record/conference': 'getCallRecordByConferenceId',
  'get&/api/DataRequestBiz/calling': 'getCalling',
  'get&/api/DataRequestBiz/queue': 'getQueue',
  'get&/api/DataRequestBiz/phones': 'getPhones',
  'put&/api/DataRequestBiz/phones/{phoneNumber}/location': 'updatePhoneLocation',
  'put&/api/Faxes/blacklist': 'updateBlackList',
  'get&/api/Faxes/blacklist': 'getBlackList',
  'put&/api/Faxes/whitelist': 'updateWhitelist',
  'get&/api/Faxes/whitelist': 'getWhitelist',
  'get&/api/Messages': 'getMessages',
  'post&/api/Messages': 'postMessages',
  'get&/api/Messages/{id}': 'getMessagesById',
  'get&/api/RecordNotifies/{id}': 'getRecordNotifiesById',
  'delete&/api/RecordNotifies/{id}': 'closeRecordNotifies',
  'post&/api/RecordNotifies': 'addRecordNotifies',
  'put&/api/RecordNotifies/{id}/invite': 'inviteRecordNotifiesUser',
  'put&/api/RecordNotifies/{id}/remove': 'removeRecordNotifiesUser',
  'get&/api/RecordNotifies/{id}/statistic': 'getRecordNotifiesTotal',
  'get&/api/RecordNotifies/{id}/members': 'getRecordNotifiesMembers',
  'post&/api/TextTemplates': 'addTextTemplates',
  'put&/api/TextTemplates/{id}': 'editTextTemplates',
  'delete&/api/TextTemplates/{id}': 'deleteTextTemplates',
  // 22-10-28
  'get&/api/Appointments/voice_notify': 'getAppointmentsVoiceNotify',
  'put&/api/Appointments/voice_notify/{id}/single': 'editAppointmentsVoiceNotifySingle',
  'get&/api/DataRequestBiz/operation_log': 'getOperationLog',
  'post&/api/Faxes/draft': 'saveFaxToDraft',
  'put&/api/Faxes/draft/{id}': 'updateDraftFax',
  'get&/api/Messages/records': 'getMessageRecords',
  'post&/api/Messages/group': 'postMessageGroup',
  'get&/api/Petstore/{id}': 'getPetById',
  'get&/api/RecordNotifies': 'getRecordNotifies',
  'get&/api/Servers/conference': 'getConferenceServers',
  'post&/api/Servers/conference': 'addConferenceServers',
  'get&/api/Servers/conference/{id}': 'getConferenceServersById',
  'put&/api/Servers/conference/{id}': 'editConferenceServers',
  'delete&/api/Servers/conference/{id}': 'deleteConferenceServers',
  'post&/api/VirtualNCDevices/{id}/trunk_group_configs/batch': 'batchEditNcTrunkGroupConfigs',
  // 22-11-16
  'get&/api/DataRequestBiz/thunk_phones': 'getThunkPhones',
  // 23-7-28
  'get&/api/Messages/templates': 'getMessageTemplates',
  'post&/api/Messages/templates': 'addMessageTemplate',
  'get&/api/Messages/templates/{id}': 'getMessageTemplateById',
  'put&/api/Messages/templates/{id}': 'editMessageTemplate',
  'delete&/api/Messages/templates/{id}': 'deleteMessageTemplate',
  'get&/api/TextTemplates/{id}': 'getTextTemplateById',
  // 23-8-1
  'put&/api/ConferenceBiz/conference/{id}': 'changeConferenceMode',
  'put&/api/Messages/conversations/{id}':'editMessageSessionName',
  'get&/api/Broadcasts/{id}':'getBroadcastById',
  'delete&/api/Broadcasts/{id}':'closeBroadcastGroup',
  'post&/api/Broadcasts':'addBroadcast',
  'get&/api/Broadcasts':'getBroadcastGroup',
  'get&/api/Broadcasts/{id}/members':'getBroadcastGroupMembers',
  'put&/api/CallBiz/call_out':'callBiz',
  'put&/api/CallBiz/forced_hook':'forcedNumber',
  'put&/api/CallBiz/answer':'answerQueueCall',
  'get&/api/Conferences/{id}':'getConferenceById',
  'delete&/api/Conferences/{id}':'closeConference',
  'post&/api/Conferences':'addConference',
  'get&/api/Conferences':'getConference',
  'put&/api/Conferences/{id}/mode':'changeConferenceMode',
  'get&/api/Conferences/{id}/members':'getConferenceMember',
};

const orgsBiz = {
  'get&/api/organizations': 'getAllRootList',
  'get&/api/organizations/{pid}/members': 'getAllDepartmentsMembers',
  'get&/api/organizations/contacts': 'getFrequentContacts',
  'get&/api/contacts/{id}': 'getUserInfo',
  'get&/api/search': 'searchKeyWordOrPid',
  'post&/api/groups/{pid}': 'createGroup',
  'delete&/api/groups/{id}': 'deleteGroup',
  'put&/api/groups/{id}': 'updateGroup',
  'get&/api/groups/{id}': 'getGroupInfo',
  'get&/api/groups/{groupId}/members': 'getGroupMembers',
  'get&/api/groups': 'getAllGroups',
  'get&/api/favorites': 'getCurrentUserFavorites',
  'get&/api/favorites/{favoriteId}': 'getCurrentUserFavoritesInfo',
  'post&/api/favorites': 'addUserFavorites',
  'post&/api/favorites/{favoriteId}/contacts': 'addUserFavoritesContact',
  'put&/api/favorites/{favoriteId}/contacts': 'updateUserFavoritesContact',
  'delete&/api/favorites/{favoriteId}': 'deleteUserFavorites',
  'post&/api/groups/{groupId}/members': 'addGroupMembers',
  'put&/api/contacts/{id}': 'updateContactUser',
  'delete&/api/contacts/{id}': 'deleteContactUser',
  'put&/api/contacts/{id}/password': 'updateContactUserPassword',
  'post&/api/contacts/{pid}': 'addContactUser',
  'put&/api/favorites/{favoriteId}': 'updateUserFavorites',
  'get&/api/favorites/{favoriteId}/contacts': 'getUserFavoritesContact',
  'put&/api/groups/{groupId}/members': 'updateGroupMembers',
  'get&/api/groups/NoContactDetail/{id}': 'getGroupDetails',
  'post&/api/organizations/{pid}': 'addOrganizations',
  'delete&/api/organizations/{id}': 'deleteOrganizations',
  'put&/api/organizations/{id}': 'updateOrganizations',
  'get&/api/organizations/{id}': 'getOrganizationsById',
  'delete&/api/organizations/{id}/All': 'deleteAllOrganizations',
  'get&/api/organizations/departments': 'getOrganizationsDepartments',
  'post&/api/Export/Organization/{pid}': 'exportOrganization',
  'post&/api/Export/PlanGroup': 'exportPlanGroup',
  'get&/api/Export/Task/{taskId}': 'getExportTask',
  'get&/api/Export/Download/{taskId}': 'getExportFileInfo',
  'get&/api/userconfigs&v2': 'getUserConfigs',
  'put&/api/userconfigs/{userId}&v2': 'updateUserConfigsById',
  'put&/api/userconfigs&v2': 'updateUserConfigs',
  'put&/api/favorites/{favoriteId}/members&v2': 'removeFavoriteMembers',
  'put&/api/groups/{id}/members&v2': 'removeGroupMembers',
  'put&/api/contacts/{id}/move&v2': 'moveContacts',
  'put&/api/contacts/{id}/top&v2': 'topContacts',
  'get&/api/contacts/{id}/{callerUserId}/departmentPaths&v2': 'getDepartmentPathsForSpecifyCaller',
  'put&/api/organizations/{id}/move&v2': 'moveNearDepartment',
  'post&/api/Import/ImportXlsOrganization': 'importOrganizationXls',
  'put&/api/groups/{id}/move&v2': 'moveGroupMember',
  'put&/api/groups/{id}/top&v2': 'topGroupMember',
  'put&/api/groups/{id}/move/group&v2': 'moveGroups',
  'get&/api/groups/self/groups&v2': 'getSelfGroups',
  // 2022-10-25
  'put&/api/contacts/{id}/password/reset': 'resetPassword',
  'put&/api/contacts/{id}/department/change&v2': 'changeDepartment',
  'get&/api/organizations/{id}/departmentPaths&v2': 'getDepartmentPathById',
  'post&/api/search/ContactByPhones&v2': 'searchContactByPhones',
  'post&/api/search/departments/batch&v2': 'searchDepartments',
  'post&/api/search/contacts/batch&v2': 'searchContacts',
  // 2022-10-28
  'post&/api/Import/ImportPlanGroup/{pid}': 'importPlanGroup',
  'get&/api/contacts/{id}/departmentPaths&v2': 'getContactDepartmentPath',
  // 2022-11-28
  'get&/api/organizations/{id}&v2': 'getOrganizationsByIdV2',
  'get&/api/organizations/{pid}/members&v2': 'getAllDepartmentsMembersV2',
  'get&/api/search&v2': 'searchKeyWordOrPidV2',
  // 23-03-14
  'get&/api/contacts/permission/departments&v2': 'getUserDepartments',
  'get&/api/groups/{id}/members&v2': 'getGroupMembersV2',
  'post&/api/groups/{pid}&v2': 'createGroupV2',
  'put&/api/groups/{id}&v2': 'updateGroupV2',
  'post&/api/groups/{id}/members&v2': 'addGroupMembersV2',
  // 23-03-21
  'delete&/api/groups/{id}/members&v2': 'deleteGroupMemberV2',
  //23-4-17
  'post&/api/import/data/organization&v2': 'importOrganization',
  'put&/api/import/data/validation&v2': 'checkData',
  'delete&/api/import/data/validation&v2': 'cancelCheckData',
  'put&/api/import/data&v2': 'importTask',
  'delete&/api/import/data&v2': 'cancelImportTask',
  'get&/api/import/organization/validation&v2': 'getCheckData',
  'get&/api/import/task/progress&v2': 'getTaskProgress',
  'get&/api/templateFiles/organization&v2': 'downloadFiles',
  //23-6-27
  'put&/api/contacts/{id}/state&v2': 'changeContactState',
  'put&/api/contacts/pinyinAndInitials&v2': 'updateContactsPinyinAndInitials',
  'get&/api/import/task/running&v2': 'importRunningTask',
  //23-7-10
  'get&/api/organizations/{pid}/descendant/members&v2': 'getDescendantMembers',
  //23-8-11
  'post&/api/upload/photo&v2': 'uploadUserAvatar',
  'put&/api/contacts/photos&v2': 'updateUserAvatar',
  'get&/api/organizations&v2': 'getRootOrganizations',
  'get&/api/groups&v2': 'getAllGroupsV2',
  'get&/api/search/statistics&v2':'searchStatistics',
};

const eventBiz = {
  'get&/api/Events': { name: 'getEvents', subBiz: 'eventBiz' },
  'post&/api/Events': { name: 'addEvents', subBiz: 'eventBiz' },
  'get&/api/Events/{id}': { name: 'getEventsById', subBiz: 'eventBiz' },
  'put&/api/Events/{id}': { name: 'updateEvents', subBiz: 'eventBiz' },
  'delete&/api/Events/{id}': { name: 'deleteEvents', subBiz: 'eventBiz' },
  'get&/api/Events/running': { name: 'getRunningEvents', subBiz: 'eventBiz' },
  'get&/api/Events/history': { name: 'getEventsHistory', subBiz: 'eventBiz' },
  'get&/api/Events/owner': { name: 'getOwnerEvents', subBiz: 'eventBiz' },
  'put&/api/Events/{id}/priority': { name: 'updateEventsPriority', subBiz: 'eventBiz' },
  'put&/api/Events/{id}/state': { name: 'updateEventsState', subBiz: 'eventBiz' },
  'put&/api/Events/{id}/preplan': { name: 'updateEventPreplan', subBiz: 'eventBiz' },
  'post&/api/EventFeedbacks': { name: 'addEventFeedBacks', subBiz: 'eventBiz' },
  'get&/api/EventFeedbacks/{eventId}/feedback': { name: 'getEventFeedBackByEventId', subBiz: 'eventBiz' },
  'get&/api/EventFeedbacks/{id}': { name: 'getEventFeedBackById', subBiz: 'eventBiz' },
  'get&/api/EventTypeGroups': { name: 'getEventTypeGroups', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups': { name: 'addEventTypeGroups', subBiz: 'eventBiz' },
  'put&/api/EventTypeGroups/{id}': { name: 'updateEventTypeGroups', subBiz: 'eventBiz' },
  'delete&/api/EventTypeGroups/{id}': { name: 'deleteEventTypeGroups', subBiz: 'eventBiz' },
  'get&/api/EventTypeGroups/{id}': { name: 'getEventTypeGroupsById', subBiz: 'eventBiz' },
  'get&/api/EventTypeGroups/{id}/children': { name: 'getEventTypeGroupsChildren', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/parent/{id}': { name: 'addEventTypeGroupsChildren', subBiz: 'eventBiz' },
  'get&/api/EventTypes': { name: 'getEventTypes', subBiz: 'eventBiz' },
  'put&/api/EventTypes/{id}': { name: 'updateEventTypes', subBiz: 'eventBiz' },
  'delete&/api/EventTypes/{id}': { name: 'deleteEventTypes', subBiz: 'eventBiz' },
  'get&/api/EventTypes/{id}': { name: 'getEventTypesById', subBiz: 'eventBiz' },
  'post&/api/EventTypes/import': { name: 'importEventTypes', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/{eventTypeGroupId}/EventTypes': { name: 'addEventTypes', subBiz: 'eventBiz' },
  'get&/api/Preplans': { name: 'getPreplans', subBiz: 'preplanBiz' },
  'get&/api/Preplans/{id}': { name: 'getPreplansById', subBiz: 'preplanBiz' },
  'put&/api/Preplans/{id}': { name: 'updatePreplans', subBiz: 'preplanBiz' },
  'delete&/api/Preplans/{id}': { name: 'deletePreplans', subBiz: 'preplanBiz' },
  'post&/api/{eventTypeId}/Preplans': { name: 'addPreplans', subBiz: 'preplanBiz' },
  'get&/api/tasks/{taskId}/feedbacks': { name: 'getFeedbacks', subBiz: 'taskBiz' },
  'get&/api/tasks/{taskId}/feedbacks/{id}': { name: 'getFeedbacksById', subBiz: 'taskBiz' },
  'post&/api/tasks/{taskId}/feedbacks': { name: 'addFeedbacks', subBiz: 'taskBiz' },
  'get&/api/Tasks/{id}': { name: 'getTasksById', subBiz: 'taskBiz' },
  'put&/api/Tasks/{id}': { name: 'updateTasks', subBiz: 'taskBiz' },
  'delete&/api/Tasks/{id}': { name: 'deleteTasks', subBiz: 'taskBiz' },
  'get&/api/event/{eventId}/Tasks': { name: 'getTasksByEventId', subBiz: 'taskBiz' },
  'post&/api/event/{eventId}/Tasks': { name: 'addTasks', subBiz: 'taskBiz' },
  'post&/api/Tasks/{parentId}/children': { name: 'addSubTasks', subBiz: 'taskBiz' },
  'get&/api/Tasks': { name: 'getTasks', subBiz: 'taskBiz' },
  'get&/api/Tasks/{id}/children': { name: 'getSubTasks', subBiz: 'taskBiz' },
  'get&/api/Tasks/owner': { name: 'getOwnerTasks', subBiz: 'taskBiz' },
  'put&/api/Tasks/{taskId}/state/{state}': { name: 'updateTasksStatus', subBiz: 'taskBiz' },
  'put&/api/events/{eventId}/Tasks/order': { name: 'updateTasksOrder', subBiz: 'taskBiz' },
  'get&/api/TaskTemplates': { name: 'getTaskTemplates', subBiz: 'taskBiz' },
  'post&/api/TaskTemplates': { name: 'addTaskTemplates', subBiz: 'taskBiz' },
  'get&/api/TaskTemplates/{id}': { name: 'getTaskTemplatesById', subBiz: 'taskBiz' },
  'put&/api/TaskTemplates/{id}': { name: 'updateTaskTemplates', subBiz: 'taskBiz' },
  'delete&/api/TaskTemplates/{id}': { name: 'deleteTaskTemplates', subBiz: 'taskBiz' },
  'get&/api/events/{eventId}/logs': { name: 'getEventLogs', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/communications': { name: 'getCommunications', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/communications/{id}': { name: 'getCommunicationsById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/communications': { name: 'connectCommunications', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/communications/{id}': { name: 'cancelConnectCommunications', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/draws': { name: 'getDraws', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/draws/{id}': { name: 'getDrawsById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/draws': { name: 'connectDraws', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/draws/{id}': { name: 'cancelConnectDraws', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/faxes': { name: 'getFaxes', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/faxes/{id}': { name: 'getFaxesById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/faxes': { name: 'connectFaxes', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/faxes/{id}': { name: 'cancelConnectFaxes', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/files': { name: 'getFiles', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/files/{id}': { name: 'getFilesById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/files': { name: 'connectFiles', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/files/{id}': { name: 'cancelConnectFiles', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/multimediatransfers': { name: 'getMultimediatransfers', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/multimediatransfers/{id}': { name: 'getMultimediatransfersById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/multimediatransfers': { name: 'connectMultimediatransfers', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/multimediatransfers/{id}': { name: 'cancelConnectMultimediatransfers', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/pictures': { name: 'getPictures', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/pictures/{id}': { name: 'getPicturesById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/pictures': { name: 'connectPictures', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/pictures/{id}': { name: 'cancelConnectPictures', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/textmessages': { name: 'getTextmessages', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/textmessages/{id}': { name: 'getTextmessagesById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/textmessages': { name: 'connectTextmessages', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/textmessages/{id}': { name: 'cancelConnectTextmessages', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/videos': { name: 'getVideos', subBiz: 'associatedBiz' },
  'get&/api/events/{eventId}/videos/{id}': { name: 'getVideosById', subBiz: 'associatedBiz' },
  'post&/api/events/{eventId}/videos': { name: 'connectVideos', subBiz: 'associatedBiz' },
  'delete&/api/events/{eventId}/videos/{id}': { name: 'cancelConnectVideos', subBiz: 'associatedBiz' },
  // 23-01-03
  'get&/api/EventTypeGroups/search': { name: 'searchEventTypeGroups', subBiz: 'eventBiz' },
  // 23-7-10
  'post&/api/Events/import': { name: 'importEvents', subBiz: 'eventBiz' },
  'get&/api/EventTypeGroups/{id}/EventTypes': { name: 'getEventTypesByGroupId', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/import': { name: 'importEventTypeGroups', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/children': { name: 'getChildEventTypeGroups', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/children/mergence': { name: 'mergeEventTypeGroup', subBiz: 'eventBiz' },
  'post&/api/EventTypeGroups/subordinates': { name: 'getEventTypeGroupsByIds', subBiz: 'eventBiz' },
  'post&/api/EventTypes/batch': { name: 'searchEventTypes', subBiz: 'eventBiz' },
  'post&/api/Preplans/batch': { name: 'searchPreplans', subBiz: 'preplanBiz' },
  'post&/api/Preplans/import': { name: 'importPreplans', subBiz: 'preplanBiz' },
  'get&/api/Preplans/template': { name: 'getPreplanTemplate', subBiz: 'preplanBiz' },
  'post&/api/taskFeedback/import': { name: 'importTaskFeedback', subBiz: 'taskBiz' },
  'post&/api/Tasks/import': { name: 'importTasks', subBiz: 'taskBiz' },
  // 23-7-28
  'get&/api/EventTypes/{id}/path': { name: 'getEventTypePath', subBiz: 'eventBiz' },
  'post&/api/EventTypes/export/relationship': { name: 'exportEventType', subBiz: 'eventBiz' },
  'post&/api/EventTypes/import/relationship': { name: 'importEventType', subBiz: 'eventBiz' },
  'post&/api/Preplans/grouping': { name: 'searchPreplanGroup', subBiz: 'preplanBiz' },
};

const viscsBiz = {
  'get&/api/Components/{name}': 'getComponentByName',
  'put&/api/Components/{name}': 'updateComponent',
  'delete&/api/Components/{name}': 'deleteComponent',
  'get&/api/Components': 'searchComponents',
  'post&/api/Components': 'createComponent',
  'get&/api/Components/export': 'exportComponents',
  'post&/api/Components/import': 'importComponents',
  'get&/api/Themes/{id}': 'getTheme',
  'put&/api/Themes/{id}': 'updateTheme',
  'delete&/api/Themes/{id}': 'deleteTheme',
  'get&/api/Themes': 'searchThemes',
  'post&/api/Themes': 'createTheme',
  'put&/api/Themes/{id}/hide': 'hiddenTheme',
  'post&/api/Themes/{id}/config/{layoutType}': 'saveThemeLayoutConfig',
  'delete&/api/Themes/{id}/config/{layoutType}': 'deleteThemeLayoutConfig',
  'get&/api/Themes/{id}/config/{layoutType}': 'getThemeLayoutConfig',
  'get&/api/Themes/export': 'exportThemes',
  'post&/api/Themes/import': 'importThemes',
  'get&/api/Themes/{id}/history/{layoutType}': 'getHistoryRecords',
  'get&/api/Themes/history/{historyId}': 'getHistoryTheme',
  'put&/api/Themes/history/{historyId}/resume': 'resumeHistoryTheme',
  'get&/api/Labels/{id}': 'getLabelById',
  'put&/api/Labels/{id}': 'editLabel',
  'delete&/api/Labels/{id}': 'deleteLabel',
  'get&/api/Labels': 'getLabels',
  'post&/api/Labels': 'addLabels',
  'get&/api/Labels/export': 'exportLabels',
  'post&/api/Labels/import': 'importLabels',
  'put&/api/Themes/{id}/move': 'moveTheme',
  // 22-10-28
  'put&/api/Components/{name}/label': 'editComponentLabel',
  'put&/api/Themes/{id}/publish': 'publishThemes',
  //23-02-15
  'post&/api/Components/search/thumbnail': 'getComponentsPoster',
  'put&/api/Components/{name}/thumbnail': 'updateComponentsPoster',
  //23-6-27
  'get&/api/Projects/{id}': 'getProjectById',
  'put&/api/Projects/{id}': 'editProject',
  'delete&/api/Projects/{id}': 'deleteProject',
  'get&/api/Projects': 'getProjects',
  'post&/api/Projects': 'addProject',
  'get&/api/Projects/{id}/export': 'exportProject',
  'post&/api/Projects/import': 'importProject',
};

const alarmBiz = {
  'post&/api/statisticians/AlarmCounter': 'getAlarmCounter',
  'get&/api/alarms/{id}': 'getAlarmsByID',
  'get&/api/alarms': 'getAlarmsByPage',
  'get&/api/alarms/GetAll': 'getAllAlarms',
  'get&/api/alarms/GetAlarmByTypeIds': 'getAlarmByTypeIds',
  'get&/api/alarms/GetAlarmsByDistrictIds': 'getAlarmsByDistrictIds',
  'get&/api/alarms/GetAlarmCounterByDistrictId': 'getAlarmCounterByDistrictId',
  'post&/api/statisticians/GetAlarmCounterByDistrictIds': 'getAlarmCounterByDistrictIds',
  'post&/api/statisticians/getAlarmCounterByOrganization': 'getAlarmCounterByOrganization',
  'get&/api/alarms/GetAlarmTypeCounterByTime': 'getAlarmTypeCounterByTime',
  'get&/api/alarms/GetAlarmDistrictCounterByTime': 'getAlarmDistrictCounterByTime',
  'get&/api/alarms/GetAlarmCounterByTime': 'getAlarmCounterByTime',
  'post&/api/alarms/GetAlarmInfo': 'getAlarmInfo',
  'post&/api/statisticians/GetAlarmCounterByTypes': 'getAlarmCounterByTypes',
  'post&/api/statisticians/AlarmCounterByTime': 'queryAlarmCounterByTime',
  'post&/api/statisticians/AlarmCounterByMinute': 'getAlarmCounterByMinute',
  'delete&/api/alarms/{id}': 'clearAlarm',
  'post&/api/alarms/Add': 'addAlarm',
  'get&/api/Preplans': 'getPreplans',
  'post&/api/Preplans': 'addPreplans',
  'get&/api/Preplans/{id}': 'getPreplanById',
  'put&/api/Preplans/{id}': 'updatePreplan',
  'delete&/api/Preplans/{id}': 'deletePreplan',
  'post&/api/statisticians/GetAlarmCounterByAlarmSourceIds': 'getAlarmCounterByAlarmSourceIds',
  'post&/api/statisticians/GetAlarmCounterByLevel': 'getAlarmCounterByLevel',
  // 22-10-28
  'put&/api/alarms/Update': 'editAlarms',
  'put&/api/alarms/ConfirmAlarm': 'confirmAlarm',
  'post&/api/statisticians/GetAlarmCounterByOrganization': 'getAlarmCounterByOrganization',
  //22-11-16
  'post&/api/ThirdAlarms': 'addThirdAlarms',
};

const quartzBiz = {
  'get&/api/Jobs': 'getJobs',
  'post&/api/Jobs': 'addJob',
  'get&/api/Jobs/{id}': 'getJobById',
  'put&/api/Jobs/{id}': 'editJob',
  'delete&/api/Jobs/{id}': 'deleteJob',
  'put&/api/Jobs/{id}/immediate_execute': 'startJob',
  'put&/api/Jobs/{id}/pause': 'stopJob',
  'put&/api/Jobs/{id}/resume': 'restoreJob',
  'post&/api/Jobs/multiple': 'addJobBiz',
  'get&/api/Jobs/multiple': 'getJobBiz',
  'get&/api/Jobs/multiple/{id}': 'getJobBizById',
  'put&/api/Jobs/multiple/{id}': 'editJobBiz',
  'delete&/api/Jobs/multiple/{id}': 'deleteJobBiz',
};

const geoDataBiz = {
  'get&/api/Districts': 'getDistricts',
  'post&/api/Districts': 'addDistricts',
  'get&/api/Districts/{id}': 'getDistrictsById',
  'put&/api/Districts/{id}': 'updateDistricts',
  'delete&/api/Districts/{id}': 'deleteDistricts',
  'post&/api/Districts/import': 'importDistricts',
  'get&/api/Districts/{parentId}/children': 'getSubDistricts',
  'post&/api/Districts/{parentId}/children': 'addSubDistricts',
  'get&/api/Districts/{id}/parents': 'getParentDistrictsById',
  'get&/api/Facilities/layers': 'getFacilityLayers',
  'post&/api/Facilities/layers/import': 'importFacilityLayers',
  'post&/api/Facilities/import': 'importFacilities',
  'post&/api/Facilities/goods/import': 'importFacilityGoods',
  'get&/api/Facilities/{id}': 'getFacilitiesById',
  'get&/api/Facilities/{id}/goods': 'getFacilityGoods',
  'post&/api/Facilities/area_query': 'getFacilityAreaQuery',
  'post&/api/Facilities/search': 'searchFacilities',
  'post&/api/Facilities/statics/generate': 'generateFacilities',
  'post&/api/Facilities/statics/files': 'getGenerateFilesName',
  'post&/api/Facilities/camera_groups/import': 'importFacilityCameraGroups',
  'get&/api/Facilities/{id}/camera_groups': 'getFacilityCameraGroups',
  'post&/api/Facilities/goods/search': 'searchFacilityGoods',
  'post&/api/Facilities/condition_query': 'queryFacilities',
  'get&/api/Statistical/layers': 'getLayersStatistical',
  'get&/api/GeoConfigs/{id}': 'getGeoConfigById',
  'put&/api/GeoConfigs/{id}': 'updateGeoConfigById',
  'get&/api/GeoConfigs': 'getGeoConfigs',
  'post&/api/GeoConfigs': 'addGeoConfigs',
  'post&/api/GeoConfigs/layer': 'addGeoLayerConfigs',
  'get&/api/GeoConfigs/layer': 'getGeoLayerConfigs',
  'put&/api/GeoConfigs/layers/{id}': 'updateGeoLayerConfigs',
  'get&/api/GeoConfigs/layers/children': 'getGeoLayerChildrenConfigs',
  'get&/api/GeoConfigs/layers/floors': 'getGeoLayerFloorsConfigs',
  'get&/api/Layers/layers': 'getLayers',
  'get&/api/Plots/{id}': 'getPlotsById',
  'put&/api/Plots/{id}': 'modifyPlotsById',
  'delete&/api/Plots/{id}': 'deletePlotsById',
  'get&/api/Plots/event': 'getEventPlots',
  'post&/api/Plots/event': 'addEventPlots',
  'get&/api/Plots/user': 'getUserPlots',
  'post&/api/Plots/user': 'addUserPlots',
  'get&/api/PlotTypes/{id}': 'getUserPlotTypesById',
  'delete&/api/PlotTypes/{id}': 'deletePlotTypesById',
  'get&/api/PlotTypes/user': 'getUserPlotTypes',
  'post&/api/PlotTypes/user': 'addUserPlotTypes',
  'get&/api/Layers/root': 'getRootLayers',
  'get&/api/Layers/children': 'getChildrenLayers',
  'get&/api/Plots': 'getPlots',
  'post&/api/Plots': 'addPlots',
  'post&/api/Boundaries': 'addBoundaries',
  'put&/api/Boundaries/{id}': 'updateBoundaries',
  'delete&/api/Boundaries/{id}': 'deleteBoundaries',
  'get&/api/Boundaries/{id}': 'getBoundariesById',
  'post&/api/Boundaries/condition_query': 'searchBoundaries',
  // 22-10-28
  'post&/api/Districts/ids': 'getDistrictsByIds',
  'get&/api/Districts/{id}/tree': 'getDistrictTreeById',
  'put&/api/Facilities/{id}/labels': 'editFacilityLabels',
  'get&/api/GeoConfigs/effect': 'getGeoEffectConfigs',
  'post&/api/GeoConfigs/effect': 'addGeoEffectConfigs',
  'put&/api/GeoConfigs/effect': 'editGeoEffectConfigs',
  'get&/api/Goods/{id}': 'getGoodsById',
  'post&/api/Goods/search': 'searchGoods',
  'get&/api/Labels/{id}': 'getLabelsById',
  'delete&/api/Labels/{id}': 'deleteLabels',
  'put&/api/Labels/{id}': 'editLabels',
  'get&/api/Labels/search': 'searchLabels',
  'post&/api/Labels': 'addLabels',
  'post&/api/Labels/import': 'importLabels',
  // 22-11-4
  'get&/api/Layers/group_keys': 'getGroupKeys',
  //22-11-16
  'post&/api/Statistical/area_query': 'queryFacilityByAreaLayer',
  // 22-12-20
  // 'post&/api/Facilities/circle_area_query': 'queryFacilitiesByCircleArea',（接口url已改变）
  // 23-01-03
  'post&/api/Facilities/circle_area': 'queryFacilitiesByCircleArea',
  'put&/api/Facilities/{id}/state': 'updateFacilityStatus',
  'post&/api/Statistical/circle_area': 'getFacilitiesCountByCircleArea',
  // 23-02-15
  'post&/api/Statistical/layers/tree': 'searchLayersTree',
  // 23-02-17
  'delete&/api/Facilities': 'multDeleteFacilities',
  'delete&/api/Goods': 'multDeleteGoods',
  // 23-03-21
  'post&/api/Layers/batch': 'getLayerInfoByIds',
  //23-4-4
  'get&/api/Layers/search': 'getBaseLayers',
  //23-4-17
  'get&/api/Facilities/{id}/scenes': 'getScenes',
  'post&/api/Scenes': 'addScenes',
  'put&/api/Scenes/{id}': 'editScene',
  'delete&/api/Scenes/{id}': 'deleteScene',
  'get&/api/Scenes/{id}': 'getSceneById',
  'get&/api/Scenes/search': 'searchScenes',
  // 23-4-18
  'get&/api/Scenes/areaCode': 'getSceneByAreaCode',
  //23-4-20
  'post&/api/Facilities/batch': 'getFacilitiesByIds',
  //23-5-4
  'get&/api/Facilities/{productId}/query': 'getFacilitiesByProductId',
  //23-6-27
  'post&/api/GeoConfigs/layers/import': 'importLayerConfig',
  //23-7-10
  'post&/api/Districts/children/mergence': 'mergeDistricts',
  'post&/api/Districts/children': 'getChildDistricts',
  'post&/api/Districts/subordinates': 'searchSubDistricts',
  'post&/api/Districts/names': 'getDistrictsByNames',
  'get&/api/GeoConfigs/{productId}/mapConfig':'getMapConfigByProductId',
  'delete&/api/Layers/batch':'deleteLayersByIds',
  'get&/api/MapServerTypes/{id}':'getMapServerType',
  'put&/api/MapServerTypes/{id}':'editMapServerType',
  'delete&/api/MapServerTypes/{id}':'deleteMapServerType',
  'post&/api/MapServerTypes':'addMapServerType',
  'get&/api/MapServerTypes':'getMapServerTypes',
  'get&/api/MapServerTypes/{id}/overlays':'getMapTypeOverlays',
  'get&/api/MapTypeOverlays/{id}':'getMapTypeOverlayById',
  'put&/api/MapTypeOverlays/{id}':'editMapTypeOverlay',
  'post&/api/MapTypeOverlays':'addMapTypeOverlay',
  'delete&/api/MapTypeOverlays':'deleteMapTypeOverlays',
};

const fileStorageBiz = {
  'get&/api/Directories/root': 'getDirectoriesRoot',
  'get&/api/Directories/{parentId}/children': 'getDirectoriesChildren',
  'get&/api/Directories/{id}': 'getDirectoriesById',
  'put&/api/Directories/{id}': 'updateDirectories',
  'delete&/api/Directories/{id}': 'deleteDirectories',
  'post&/api/Directories': 'addDirectories',
  'get&/api/Files': 'getFiles',
  'get&/api/Files/{fileId}': 'getFilesById',
  'put&/api/Files/{fileId}': 'updateFiles',
  'delete&/api/Files/{fileId}': 'deleteFiles',
  'post&/api/Files/ss': 'addSS',
  'put&/api/Files/recordnotify/{fileId}': 'updateRecordFiles',
  'post&/api/Files/wts': 'addWTS',
  'get&/api/ZEnums/StorageKind': 'getStorageKind',
  //23-02-15
  'get&/api/Files/search': 'searchFiles',
  // 23-7-10
  'get&/api/Directories': 'getDirectories',
};

const geoAnalysisBiz = {
  'get&/api/Buildings': 'getBuildings',
  'get&/api/Geocoder/geocoding': 'getGeocoding',
  'get&/api/Geocoder/reverse_geocoding': 'getGeocodingReverse',
  'get&/api/Navigation/driving': 'getDrivingNavigation',
  'get&/api/Navigation/walking': 'getWalkingNavigation',
  'get&/api/Navigation/riding': 'getRidingNavigation',
  'get&/api/Poi': 'getPoi',
  'get&/api/Poi/place_suggestion': 'getPlaceSuggestion',
  'get&/api/Traffic': 'getTraffic',
};

const preplanAnalysisBiz = {
  'get&/DangerousSources': 'getDangerousSources',
  'get&/KeyProtections': 'getKeyProtections',
  'get&/Shelters': 'getShelters',
  'get&/Warehouses': 'getWarehouses',
  'get&/EmergencyFacilities': 'getEmergencyFacilities',
  'get&/ManpowerResources': 'getManpowerResources',
  'get&/MedicalResources': 'getMedicalResources',
  'get&/Alarm/DangerousSources': 'getDangerousSourcesByAlarmId',
  'get&/Alarm/KeyProtections': 'getKeyProtectionsByAlarmId',
  'get&/Alarm/Shelters': 'getSheltersByAlarmId',
  'get&/Alarm/Warehouses': 'getWarehousesByAlarmId',
  'get&/Alarm/EmergencyFacilities': 'getEmergencyFacilitiesByAlarmId',
  'get&/Alarm/ManpowerResources': 'getManpowerResourcesByAlarmId',
  'get&/Alarm/MedicalResources': 'getMedicalResourcesByAlarmId',
  'get&/Alarm/PollutionSources': 'getPollutionSourcesByAlarmId',
  'get&/api/AlarmFacilitiesStatistics': 'getAlarmFacilitiesStatistics',
  'get&/api/EventFacilitiesStatistics': 'getEventFacilitiesStatistics',
  'post&/api/EventFacilitiesStatistics': 'queryEventFacilitiesStatistics',
  // 22-11-4
  'get&/api/EventFacilities': 'getEventFacilitiesByGroupKey',
  // 23-5-30
  'get&/api/AlarmFacilities': 'getAlarmFacilitiesByGroupKey',
};

const modelAnalysisBiz = {
  'post&/api/Analysis/GetAnalysisGaussianPlumeData': 'getAnalysisGaussianPlumeData',
  'post&/api/Analysis/GetAnalysisDiffusionArea': 'getAnalysisDiffusionArea',
  'post&/api/Analysis/GetAnalysisDiffusionTrend': 'getAnalysisDiffusionTrend',
  'post&/api/Analysis/AnalysisVaporCloudExplosion': 'getAnalysisVaporCloudExplosion',
  'get&/api/Gas': 'getGas',
  'get&/api/Gas/{id}': 'getGasById',
  'get&/api/Gas/Name/{name}': 'getGasByName',
  'get&/api/ExceptionDemo/{resourceId}': 'showCustomValidationException',
  'delete&/api/ExceptionDemo/{resourceId}': 'showUnHandleException',
  'post&/api/ExceptionDemo': 'showForbiddenException',
  'post&/api/Analysis/gaussian_plume&v2': 'getAnalysisGaussianPlumeDataV2',
  'post&/api/Analysis/gaussian_plume/area&v2': 'getAnalysisDiffusionAreaV2',
  'post&/api/Analysis/gaussian_plume/trend&v2': 'getAnalysisDiffusionTrendV2',
  'get&/api/Gas/name&v2': 'getGasByNameV2',
  // 22-10-28
  'post&/api/Analysis/vapor_cloud_explosion&v2': 'getAnalysisVaporCloudExplosionV2',
  // 22-11-28
  'get&/api/Gas&v2': 'getGasV2',
  'get&/api/Gas/{id}&v2': 'getGasByIdV2',
};

const videoFusionServiceBiz = {
  'get&/api/Cameras/{id}': 'getCameraById',
  'get&/api/Cameras/groups': 'getCameraByGroup',
  'get&/api/Cameras/{id}/playUrls': 'getCameraPlayUrlsById',
  'get&/api/Cameras/groups/{groupId}': 'getCameraListById',
  'post&/api/FavoriteCameraItems/sub': 'saveFavoriteCameraItems',
  'get&/api/FavoriteCameraItems': 'getFavoriteCameraItems',
  'delete&/api/FavoriteCameraItemTypes/{type}/FavoriteCameraItems/{id}': 'deleteFavoriteCameraItem',
  'get&/api/Cameras/search': 'cameraSearchByKey',
  'post&/api/Cameras/groups': 'createMonitoringPlanGroup',
  'delete&/api/Cameras/groups/{groupId}/children/{cameraId}': 'deletePlanGroupMonitoring',
  'post&/api/Cameras/groups/children': 'collectionMonitoringToPlanGroup',
  'put&/api/Cameras/groups/{id}': 'editMonitoringPlanGroup',
  'get&/api/Cameras/groups/{id}/preplan_cameras': 'getPreplanCameras',
  'put&/api/Cameras/groups/{id}/children': 'removeCamera',
  'put&/api/Cameras/groups/{id}/order': 'sortPlansGroup',
  'get&/api/Statistics/cameras': 'getCameras',
  'get&/api/Statistics/cameras/fault': 'getFaultCameras',
  'get&/api/Statistics/cameras/bad': 'getBadCameras',
  'get&/api/Statistics/cameras/resolution': 'getCamerasResolution',
  'get&/api/Statistics/detectionTasks/history': 'getDetectionTasksHistory',
  'get&/api/Statistics/detectionTasks/{jobId}/quality': 'getCamerasByJobId',
  'get&/api/Statistics/detectionTasks/{jobId}/bad': 'getBadCamerasByJobId',
  'get&/api/Statistics/detectionTasks/{jobId}/fault': 'getFaultCamerasByJobId',
  'get&/api/Statistics/favoriteCameraGroup': 'getFavoriteCameraGroupTotal',
  'get&/api/Cameras/area_query': 'getCamerasByArea',
  'get&/api/VideoConferences/live/{conferenceNumber}': 'obtainConferenceLive',
  'put&/api/VideoConferences/{conferenceNumber}/to_live': 'videoConferenceToLive',
  'get&/api/Label': 'getAllLabels',
  'post&/api/Label': 'createLabel',
  'put&/api/DetectionTasks/{id}/pause': 'pauseDetectionTasks',
  'put&/api/DetectionTasks/{id}/resume': 'resumeDetectionTasks',
  'put&/api/DetectionTasks/{id}/stop': 'stopDetectionTasks',
  'get&/api/DetectionTasks/{id}/records': 'getDetectionTaskRecords',
  'get&/api/DetectionTasks/{id}': 'getDetectionDetails',
  'get&/api/DetectionTasks': 'getDetectionTasks',
  'get&/api/Cameras/{id}/preplan_groups': 'getPreplanGroupsByCameraId',
  'get&/api/Cameras/{id}/detection_records': 'getCameraDetectionRecords',
  'get&/api/Cameras/advance_search': 'searchCameras',
  'put&/api/Cameras/{id}/control': 'controlCameras',
  'put&/api/Cameras/{id}/videos/start': 'startVideoRecording',
  'put&/api/Cameras/{id}/videos/stop': 'stopVideoRecording',
  'put&/api/Cameras/{id}/pictures': 'cameraScreenshot',
  'get&/api/Cameras/mediarecords': 'getMediaRecords',
  'get&/api/Cameras/{id}/isvideoing': 'getUserInVideoById',
  'post&/api/FavoriteCameraItems/import': 'importFavoriteCameraItems',
  'post&/api/FavoriteCameraItems': 'createFavoriteCameraItem',
  'get&/api/FavoriteCameraItems/root': 'getRootFavoriteCameraItems',
  'get&/api/FavoriteCameraItems/{parentId}/children': 'getChildrenFavoriteCameraItems',
  'put&/api/FavoriteCameraItems/{id}': 'editFavoriteCameraItem',
  'put&/api/Cameras/{id}': 'editCamera',
  'get&/api/Cameras/detection/search': 'searchDetectionData',
  'get&/api/Cameras/detection/download': 'downloadDetectionData',
  'put&/api/Lives/open': 'openLiveWithInfo',
  'get&/api/Cameras/{id}/favorite_groups': 'getFavoriteGroupsById',
  'get&/api/Lives': 'obtainLive',
  'get&/api/Lives/{stream}/video_records': 'getVideoRecords',
  'put&/api/Lives': 'openLives',
  'post&/api/Lives': 'createLives',
  'get&/api/CameraGroups': 'getCameraGroups',
  'get&/api/CameraGroups/{id}/children': 'getChildrenCameraGroupsById',
  'post&/api/Cameras': 'addCameras',
  'get&/api/DetectionTasks/newest_effective': 'getLatestEffective',
  'post&/api/GbConfigs/sync_domain': 'syncGbConfigDomain',
  'put&/api/GbConfigs/domains/{id}': 'editGbConfigDomain',
  'get&/api/GbConfigs/domains/{id}': 'getGbConfigDomainById',
  'get&/api/GbConfigs/domains': 'getGbConfigDomains',
  'post&/api/GbConfigs/domains': 'addGbConfigDomains',
  'get&/api/GbConfigs/unused_domains': 'getUnusedDomains',
  'post&/api/GbConfigs/domains/batch': 'deleteDomains',
  'delete&/api/GbConfigs/domains/{id}/data': 'clearDomains',
  'get&/api/GbConfigs/domains/{id}/syncTaskHistories': 'getSyncTaskHistories',
  'get&/api/GbConfigs/domains/syncTaskHistories/{id}/records': 'getSyncTaskHistoriesById',
  'get&/api/GbConfigs/domains/{id}/expired': 'getExpiredDomains',
  'post&/api/GbConfigs/domains/{id}/expired/batch': 'deleteExpiredDomains',
  'get&/api/HistoryCameraPulls': 'searchHistoryCameraPulls',
  'get&/api/MediaServers': 'getAllMediaServers',
  'post&/api/MediaServers': 'addMediaServers',
  'delete&/api/MediaServers/{id}': 'deleteMediaServers',
  'get&/api/MediaSessions': 'getMediaSessions',
  'get&/api/Signals': 'getSignals',
  'put&/api/Signals': 'editSignals',
  'put&/api/VideoConferences/{conferenceNumber}/invite_camera': 'editInviteCamera',
  'put&/api/VideoConferences/{conferenceNumber}/invite_live': 'editInviteLive',
  // 22-10-28
  'put&/api/CameraGroups/camera/batch': 'batchAddCameraToGroup',
  'post&/api/CameraGroups/batch': 'searchCameraGroups',
  'delete&/api/Cameras/groups/{id}': 'deleteCameraGroup',
  'put&/api/Cameras/onVif_cameras/discovery': 'searchOnVif',
  'put&/api/Cameras/{id}/location': 'editCameraLocation',
  'post&/api/Cameras/search/label': 'searchCamerasByLabel',
  'post&/api/CameraVideos': 'startCameraVideo',
  'put&/api/CameraVideos/{id}/stop': 'stopCameraVideo',
  'post&/api/DetectionTasks/newest_effectives': 'getLatestDetectionTasks',
  // 22-11-4
  'put&/api/FavoriteCameraItems/{subType}/{subId}/batch': 'batchEditFavoriteCameraItems',
  // 22-11-16
  'put&/api/CameraGroups/{id}': 'editCameraGroups',
  'put&/api/Label/{id}': 'editLabel',
  'delete&/api/Label/{id}': 'deleteLabel',
  'delete&/api/Label/batch': 'batchDeleteLabel',
  'post&/api/Label/camera/batch': 'batchEditCameraLabel',
  'delete&/api/Label/camera/batch': 'batchDeleteCameraLabel',
  // 22-11-18
  'get&/api/CameraGroups/Search': 'queryCameraGroups',
  'get&/api/Statistics/detectionTasks/{jobId}/history': 'getDetectionHistoryByJobId',
  'get&/api/Cameras/Search&v2': 'searchCamerasV2',
  // 22-11-28
  'post&/api/Cameras/advance_search&v2': 'advanceSearchCameras',
  'get&/api/Label&v2': 'getAllLabelsV2',
  // 23-03-14
  'get&/api/HistoryCameraPulls/search': 'getHistoryCameraPulls',
  'get&/api/HistoryCameraPulls/{id}': 'getHistoryCameraPullsById',
  'get&/api/MediaSessions/{id}': 'getMediaSessionsById',
  'get&/api/MediaSessions/statistics': 'getMediaSessionStatistics',
  'get&/api/MediaSessions&v2': 'getMediaSessionsV2',
  // 23-03-21
  'post&/api/Cameras/import': 'importCameras',
  'post&/api/Cameras/batch': 'getCameraInfoByIds',
  //23-4-17
  'post&/api/Cameras/images/batch': 'queryMonitorScreenshot',
  'put&/api/Cameras/areaCode/batch': 'editCamerasAreaCode',
  'get&/api/Cameras/areaCode/{areaCode}': 'getCamerasByAreaCode',
  // 23-4-18
  'post&/api/Cameras/areaCode/search': 'searchCamerasByAreaCode',
  'get&/api/Cameras/{id}/videos': 'getVideosById',
  //23-6-27
  'post&/api/Recording': 'startSteamRecording',
  'get&/api/Recording': 'getSteamRecordingInfo',
  'put&/api/Recording/{streamId}/status': 'editSteamRecordingStatus',
  'delete&/api/Recording/{id}': 'deleteRecording',
  'post&/api/Recording/batch/delete': 'batchDeleteRecording',
  'get&/api/Recording/search': 'searchRecording',
  // 23-7-28
  'put&/api/Cameras/{id}/playback_control': 'setCameraPlayback',
  'put&/api/CameraGroups/{id}/move': 'moveCameraGroup',
  'put&/api/CameraGroups/{id}/children': 'batchAddCameraGroup',
  'put&/api/CameraGroups/{id}/camera/move': 'moveCamera',
  'delete&/api/CameraGroups/{id}/children/{subGroupId}': 'deleteSubGroup',
  'post&/api/CameraGroups/group': 'addSubGroup',
  'get&/api/Cameras/{id}/recordingInfo': 'getCameraRecordingInfo',
  'post&/api/StreamKeepAliveJobs': 'addStreamKeepAliveJob',
  'get&/api/StreamKeepAliveJobs': 'getStreamKeepAliveJobs',
  'get&/api/StreamKeepAliveJobs/{id}': 'getStreamKeepAliveJobById',
  'delete&/api/StreamKeepAliveJobs/{id}': 'deleteStreamKeepAliveJob',
  'put&/api/StreamKeepAliveJobs/{id}': 'editStreamKeepAliveJob',
  'put&/api/StreamKeepAliveJobs/{id}/status': 'editStreamKeepAliveJobStatus',
  'get&/api/StreamKeepAliveJobs/{id}/task': 'getStreamKeepAliveTasks',
  'get&/api/StreamKeepAliveJobs/{id}/record': 'getStreamKeepAliveRecords',
  'post&/api/UpperDomains': 'addUpperDomain',
  'get&/api/UpperDomains': 'getUpperDomains',
  'put&/api/UpperDomains/{id}': 'editUpperDomain',
  'delete&/api/UpperDomains/{id}': 'deleteUpperDomain',
  'get&/api/UpperDomains/{id}': 'getUpperDomainById',
  'get&/api/UpperDomains/{id}/syncTaskHistories': 'getUpperDomainSyncHistory',
  'get&/api/UpperDomains/syncTaskHistories/{id}/records': 'getUpperDomainSyncRecords',
  'post&/api/Lives/{stream}': 'sendAudio',
  'get&/api/Lives/{stream}': 'getLiveInfo',
  'delete&/api/Lives/{stream}': 'closeLive',
  'put&/api/CameraGroups/{id}/camera/top': 'moveCameraTop',
  'post&/api/Cameras/circle_area': 'searchCircleAreaCamera',
  'post&/api/LowerDomains/sync': 'syncLowerDomains',
  'put&/api/LowerDomains/{id}': 'editLowerDomains',
  'get&/api/LowerDomains/{id}': 'getLowerDomainById',
  'get&/api/LowerDomains': 'getLowerDomains',
  'post&/api/LowerDomains': 'addLowerDomain',
  'get&/api/LowerDomains/unused_domains': 'getUnusedLowerDomains',
  'post&/api/LowerDomains/batch': 'batchDeleteLowerDomains',
  'delete&/api/LowerDomains/{id}/data': 'clearLowerDomains',
  'get&/api/LowerDomains/{id}/syncTaskHistories': 'getLowerDomainsSyncHistories',
  'get&/api/LowerDomains/syncTaskHistories/{id}': 'getSyncTaskHistoryById',
  'get&/api/LowerDomains/syncTaskHistories/{id}/records': 'searchSyncTaskHistory',
  'get&/api/LowerDomains/{id}/expired': 'getExpiredLowerDomains',
  'post&/api/LowerDomains/{id}/expired/batch': 'batchDeleteExpiredLowerDomains',
  'put&/api/LowerDomains/{id}/Conflict': 'resolveLowerDomainsConflict',
  'get&/api/LowerDomains/{id}/state/records': 'getLowerDomainStateRecords',
  'get&/api/UpperDomains/{id}/state/records': 'getUpperDomainStateRecords',
  'get&/api/Cameras/state/records': 'getCameraState',
  'get&/api/UpperDomains/cameras/state/records': 'getCamerasStateHistory',
  'post&/api/CameraGroups/subordinates':'getCameraGroupSubordinates',
  'get&/api/CameraGroups/advance_search':'searchGroupAndCamera',
  'get&/api/CurrentDomains':'getCurrentDomains',
  'get&/api/UpperDomains/syncTaskHistories/{id}':'getUpperSyncTaskHistoryById',
  'post&/api/Cameras&v2':'addGbCamera',
  'put&/api/Cameras/{id}&v2':'updateGbCamera',
  'post&/api/Cameras/nonstandard&v2':'addNonStandardCamera',
  'put&/api/Cameras/nonstandard/{id}&v2':'updateNonStandardCamera',
  'post&/api/Cameras/virtual&v2':'addVirtualFile',
  'put&/api/Cameras/virtual/{id}&v2':'updateVirtualFileCamera',
  'post&/api/Cameras/id&v2':'generateGbId',
  'put&/api/LowerDomains/{id}/expired':'updateExpiredLowerDomains',
  'post&/api/CameraGroups/{id}/cameras/batch':'batchAddCamerasToGroup',
};

const boundaryBiz = {
  'get&/resource/api/citydata/{areaCode}/boundary/boundary.json': 'getPrimaryAreaBoundary',
  'get&/resource/api/citydata/{primaryAreaCode}/districts/{englishName}.json': 'getChildDistrictBoundary',
};

const resourceBiz = {
  'get&': 'getJsonDataByUrl',
  'get&/resource/api/': 'getResourceData',
  'get&/resource/api/citydata/': 'getCityData',
  'get&/resource/api/commondata/': 'getCommonData',
  'get&/resource/api/projectdata/': 'getProjectData',
};

const facilityBiz = {
  'get&/api/Facilities/layers': 'getAllFacilityType',
  'post&/api/Facilities/area_query': 'getFacilitiesByArea',
  'get&/api/Facilities/{id}/goods': 'getGoods',
  'get&/api/Facilities/{id}': 'getFacilitiesById',
  'post&/api/Facilities/condition_query': 'getFacilitiesByCondition',
};

const vcsBiz = {
  'get&/api/Accounts': 'getAccounts',
  'post&/api/Accounts': 'addAccounts',
  'get&/api/Accounts/{id}': 'getAccountsById',
  'delete&/api/Accounts/{id}': 'deleteAccounts',
  'get&/api/Accounts/name/{name}': 'getAccountsByName',
  'get&/api/Conferences/{id}': 'getConferencesById',
  'delete&/api/Conferences/{id}': 'endConferences',
  'get&/api/Conferences/number/{number}': 'getConferencesByNumber',
  'delete&/api/Conferences/number/{number}': 'endConferencesByNumber',
  'get&/api/Conferences/number/{number}': 'getConferencesLayoutById',
  'get&/api/Conferences/{id}/layout/cascade': 'getCascadeConferencesLayoutById',
  'put&/api/Conferences/{id}/layout/cascade': 'editCascadeConferencesLayout',
  'get&/api/Conferences/{id}/presenters': 'getConferencesPresenters',
  'get&/api/Conferences/{id}/conventioneers': 'getConferencesConventioneers',
  'get&/api/Conferences/{id}/broadcaster': 'getConferencesBroadcaster',
  'get&/api/Conferences/{id}/record': 'getConferencesRecord',
  'put&/api/Conferences/{id}/record': 'recordConferences',
  'get&/api/Conferences/{id}/invitation': 'getConferencesInvitation',
  'put&/api/Conferences/{id}/phone': 'inviteMeetingByPhone',
  'put&/api/Conferences/{id}/account': 'inviteMeetingByAccount',
  'put&/api/Conferences/{id}/terminal': 'inviteMeetingByTerminal',
  'put&/api/Conferences/{id}/rtsp': 'inviteMeetingByRtsp',
  'put&/api/Conferences/{id}/other': 'inviteMeetingByOther',
  'post&/api/Conferences': 'addConferences',
  'put&/api/Conferences/{id}/kick': 'kickConventioneers',
  'put&/api/Conferences/{id}/mute': 'setConventioneersMute',
  'put&/api/Conferences/{id}/silence': 'setConventioneersSilence',
  'put&/api/Conferences/{id}/isolate': 'setConventioneersIsolate',
  'put&/api/Conferences/{id}/broadcast': 'setConventioneersBroadcast',
  'put&/api/Conferences/{id}/screen': 'setConventioneersScreen',
  'put&/api/Conferences/{id}/layout/default': 'setConferencesDefaultLayout',
  'put&/api/Conferences/{id}/subtitle': 'setConferencesSubtitle',
  'put&/api/Conferences/{id}/presenter': 'openConferencesLive',
  'put&/api/Conferences/{id}/keepalive': 'keepaliveConferences',
  'get&/api/MCUData/type': 'getMcuType',
  'get&/api/MCUData': 'getMcuData',
  'post&/api/MCUData': 'addMcuData',
  'get&/api/MCUData/{id}': 'getMcuDataById',
  'put&/api/MCUData/{id}': 'editMcuData',
  'delete&/api/MCUData/{id}': 'deleteMcuData',
  'get&/api/PlatformData/default': 'getDefaultPlatformData',
  'get&/api/PlatformData/type/{type}/{id}': 'getPlatformDataById',
  'get&/api/PlatformData/type/{type}/ip/{ip}': 'getPlatformDataByIp',
  'get&/api/PlatformData': 'getPlatformData',
  'get&/api/PlatformData/strategy': 'getPlatformStrategy',
  'get&/api/PlatformData/config': 'getPlatformConfig',
  'get&/api/Recordings': 'getRecordings',
  'get&/api/TerminalOrganizations/{id}/terminals': 'getOrganizationTerminal',
  'get&/api/TerminalOrganizations/{id}': 'getOrganizationsById',
  'get&/api/TerminalOrganizations': 'getOrganizations',
  'get&/api/TerminalOrganizations/root': 'getRootOrganizations',
  'get&/api/TerminalOrganizations/{parentID}/children': 'getChildOrganizations',
  'get&/api/Terminals': 'getTerminals',
  'post&/api/Terminals': 'addTerminals',
  'get&/api/Terminals/{id}': 'getTerminalsById',
  'delete&/api/Terminals/{id}': 'deleteTerminals',
  'get&/api/Terminals/number/{number}': 'getTerminalsByNumber',
  // 22-10-28
  'get&/api/Conferences/{id}/layout': 'getConferenceLayoutById',
  'put&/api/Conferences/{id}/layout': 'editConferenceLayout',
  'put&/api/Conferences/{id}/isCascade': 'editConferenceCascade',
  'put&/api/Conferences/{id}/live': 'openConferenceLive',
  // 22-11-28
  'get&/api/Conferences/{id}/hide_conventioneers': 'getHideConventioneers',
  //23-6-27
  'put&/api/Terminals/{id}': 'editTerminal',
  'put&/api/Conferences/{id}/reName': 'editConferenceName',
  'put&/api/Conferences/{id}/openCamera': 'openConferenceCamera',
  'put&/api/Conferences/{id}/closeCamera': 'closeConferenceCamera',
  'put&/api/Conferences/{id}/focus': 'setConferenceFocus',
  'post&/api/TerminalOrganizations/terminals/batch':'searchTerminalOrganizations',
  'get&/api/Search':'searchTerminalAndGroup',
};

const auditBiz = {
  'get&/api/Operation': 'getOperation',
  'post&/api/Operation': 'searchOperation',
  'get&/api/Record/{id}': 'getRecordById',
};

const assetBiz = {
  'put&/api/Client': 'getClientOverview',
  'get&/api/Client': 'getClients',
  'post&/api/Client': 'addClient',
  'get&/api/Client/{id}': 'getClientsById',
  'put&/api/Client/{id}': 'editClient',
  'delete&/api/Client/{id}': 'deleteClient',
  'put&/api/Device': 'getDeviceOverview',
  'get&/api/Machines': 'getMachines',
  'post&/api/Machines': 'addMachines',
  'get&/api/Machines/{id}': 'getMachineById',
  'put&/api/Machines/{id}': 'editMachine',
  'delete&/api/Machines/{id}': 'deleteMachine',
  'get&/api/MCU': 'getMcu',
  // 'get&/api/NC/{id}/phones': 'getNcPhones',
  // 'get&/api/NC/{id}/trunk_group_configs': 'getNcTrunkGroupConfigs',
  'put&/api/Networks': 'getNetworksOverview',
  'get&/api/Networks': 'getNetworks',
  'post&/api/Networks': 'addNetworks',
  'get&/api/Networks/{id}': 'getNetworkById',
  'put&/api/Networks/{id}': 'editNetwork',
  'delete&/api/Networks/{id}': 'deleteNetwork',
  'put&/api/Platforms': 'getPlatformsOverview',
  'get&/api/Platforms': 'getPlatforms',
  'post&/api/Platforms': 'addPlatform',
  'get&/api/Platforms/{id}': 'getPlatformById',
  'put&/api/Platforms/{id}': 'editPlatform',
  'delete&/api/Platforms/{id}': 'deletePlatform',
  'put&/api/Terminals': 'getTerminals',
  // 9-30
  'get&/api/PositionEquipment': 'getPositionEquipment',
  'post&/api/PositionEquipment': 'addPositionEquipment',
  'get&/api/PositionEquipment/{id}': 'getPositionEquipmentById',
  'put&/api/PositionEquipment/{id}': 'editPositionEquipment',
  'delete&/api/PositionEquipment/{id}': 'deletePositionEquipment',
  'get&/api/Statistics/Overview': 'getStatisticsOverview',
  // 10-10
  'get&/api/Statistics/Overview/Client': 'getStatisticsClientOverview',
  'get&/api/Statistics/Overview/Terminal': 'getStatisticsTerminalOverview',
  // 2022-10-25
  'get&/api/MCU/{id}': 'getMcuById',
  'get&/api/MCU/terminal': 'getMcuTerminal',
  // 'get&/api/NC': 'getNc',
  // 'get&/api/NC/{id}': 'getNcById',
  'get&/api/Terminals': 'searchTerminals',
  // 22-10-28
  'post&/api/Terminals': 'addTerminals',
  'get&/api/Terminals/{id}': 'getTerminalById',
  'put&/api/Terminals/{id}': 'editTerminal',
  'delete&/api/Terminals/{id}': 'deleteTerminal',
  // 22-11-09
  'get&/api/Assets/{type}/ip/{ip}': 'getAssetsByIp',
  'get&/api/Device': 'getDevice',
  'post&/api/Device': 'addDevice',
  'get&/api/Device/{id}': 'getDeviceById',
  'put&/api/Device/{id}': 'editDevice',
  'delete&/api/Device/{id}': 'deleteDevice',
  'post&/api/Platforms/search': 'searchPlatformsById',
  'post&/api/Terminals/search': 'searchTerminalsById',
  // 22-12-20
  'post&/api/Assets/{id}/status/report': 'reportAssetsStatus',
  // 23-4-4
  'put&/api/Topologys/{id}': 'editTopology',
  'get&/api/Topologys': 'getTopology',
  // 23-4-7
  'post&/api/Statistics/Area/Terminal': 'getTerminalByArea',
  'post&/api/Statistics/Area/Platform': 'getPlatformByArea',
  //23-4-17
  'get&/api/Assets/{id}': 'getAssetById',
  'post&/api/Assets': 'searchAssets',
  'put&/api/Terminals/SyncVcsTerminal': 'syncVcsTerminal',
  //23-5-4
  'put&/api/Assets/ReloadCache': 'reloadCache',
  'post&/api/Client/import': 'importClient',
  'post&/api/Device/import': 'importDevice',
  'post&/api/Networks/import': 'importNetworks',
  'delete&/api/Platforms/Batch': 'deletePlatforms',
  'post&/api/Platforms/import': 'importPlatforms',
  'post&/api/PositionEquipment/import': 'importPositionEquipment',
  'delete&/api/Terminals/Batch': 'deleteTerminals',
  'post&/api/Terminals/import': 'importTerminals',
  //23-6-27
  'post&/api/Assets/contacts': 'searchContacts',
  'get&/api/Metrics/{id}': 'getMetricsById',
  'put&/api/Metrics/{id}': 'editMetrics',
  'delete&/api/Metrics/{id}': 'deleteMetrics',
  'get&/api/Metrics': 'getMetrics',
  'post&/api/Metrics': 'addMetrics',
  'post&/api/Metrics/import': 'importMetrics',
  'post&/api/Statistics/Overview/Search': 'overviewByPrefixAreaCodes',
  'post&/api/Statistics/Overview/Client/Search': 'clientOverviewByPrefixAreaCodes',
  'post&/api/Statistics/Overview/Terminal/Search': 'terminalOverviewByPrefixAreaCodes',
  'get&/api/Terminals/source': 'getTerminalSource',
  'get&/api/Terminals/source/number': 'getTerminalSourceByNumber',
  'get&/api/TypeConfigs/{id}': 'getTypeConfig',
  'put&/api/TypeConfigs/{id}': 'editTypeConfig',
  'delete&/api/TypeConfigs/{id}': 'deleteTypeConfig',
  'get&/api/TypeConfigs': 'getTypeConfigs',
  'post&/api/TypeConfigs': 'addTypeConfig',
  'post&/api/TypeConfigs/import': 'importTypeConfigs',
  'post&/api/Assets/search': 'commonAssetSearch',
  'post&/api/Assets/circle_area': 'searchCircleAreaAsset',
  'get&/api/Nc':'getNc',
  'get&/api/Nc/{id}':'getNcById',
  'get&/api/Nc/{id}/phones':'getNcPhones',
  'get&/api/Nc/{id}/trunk_group_configs':'getNcTrunkGroupConfigs',
  'post&/api/Statistics/MonitorDevice':'getMonitorDeviceStatistics',
};

const alertsPlatformBiz = {
  'get&/api/AlertRecords': 'getAlertRecords',
  'get&/api/AlertRecords/{id}': 'getAlertRecordById',
  'put&/api/AlertRecords/{id}/resolve': 'cancelAlertRecord',
  'get&/api/AlertSourceTypes': 'getAlertSourceTypes',
  'get&/api/AlertTypes/root': 'getRootAlertTypes',
  'get&/api/AlertTypes/{id}/children': 'getChildAlertTypes',
  'get&/api/AlertTypes/{id}': 'getAlertTypeById',
  'post&/api/AlertTypes': 'addAlertType',
  'get&/api/AlertSourceTypes/{id}': 'getAlertSourceTypeById',
  'put&/api/AlertSourceTypes/{id}': 'updateAlertSourceType',
  //23-03-21
  'post&/api/AlertTypes/batch': 'getAlertTypeInfoByIds',
  //23-4-4
  'post&/api/AlertRecords/search': 'searchAlertRecords',
  //23-6-27
  'get&/api/AlertTypes': 'getAlertTypes',
  'post&/api/AlertTypes/subordinates': 'getSubordinateAlertTypes',
  //23-7-10
  'post&/api/AlertTypes/children/mergence': 'mergeChildAlertType',
  'post&/api/AlertTypes/children': 'searchSubAlertTypes',
  'post&/api/AlertTypes/import': 'importAlertTypes',
  'post&/api/AlertTypes/reload': 'reloadAlertTypes',
  'post&/api/AlertRecords': 'addAlertRecord',
};

const dasBiz = {
  'get&/api/JobMetaManage/GetAllSimpleJobMetaModel': 'getAllSimpleJobMetaModel',
  'get&/api/JobMetaManage/GetAllLabel': 'getAllLabel',
  'get&/api/JobMetaManage/GetJobMetaModelById': 'getJobMetaModelById',
  'post&/api/JobMeta/ExecuteJobMeta': 'executeJobMeta',
};

const scheduleBiz = {
  'get&/api/MatterTimeConfigs': 'getMatterTimeConfigs',
  'post&/api/MatterTimeConfigs': 'addMatterTimeConfigs',
  'get&/api/MatterTimeConfigs/{id}': 'getMatterTimeConfigsById',
  'put&/api/MatterTimeConfigs/{id}': 'updateMatterTimeConfigs',
  'delete&/api/MatterTimeConfigs/{id}': 'deleteMatterTimeConfigs',
  'post&/api/ScheduleMatters': 'addScheduleMatters',
  'get&/api/ScheduleMatters': 'getScheduleMatters',
  'get&/api/ScheduleMatters/{id}': 'getScheduleMattersById',
  'put&/api/ScheduleMatters/{id}': 'updateScheduleMatters',
  'get&/api/ScheduleMatters/other': 'getQts',
  'put&/api/ScheduleMatters/{id}/single': 'updateSingleScheduleMatter',
  'delete&/api/ScheduleMatters/{id}': 'deleteScheduleMatter',
  'get&/api/ScheduleMatters/member': 'searchScheduleMember',
};

const rrsBiz = {
  'get&/api/MainResources': 'getMainResources',
  'post&/api/MainResources': 'addMainResources',
  'get&/api/MainResources/{id}': 'getMainResourcesById',
  'put&/api/MainResources/{id}': 'updateMainResources',
  'delete&/api/MainResources/{id}': 'deleteMainResources',
  'get&/api/Resources': 'getResources',
  'post&/api/Resources': 'addResources',
  'get&/api/Resources/{id}': 'getResourcesById',
  'put&/api/Resources/{id}': 'editResources',
  'delete&/api/Resources/{id}': 'deleteResources',
  'get&/api/ResourceTypes': 'getResourceTypes',
  'post&/api/ResourceTypes': 'addResourceType',
  'get&/api/ResourceTypes/{id}': 'getResourceTypeById',
  'put&/api/ResourceRelationships': 'editResourceRelationships',
  // 23-03-23
  'post&/api/ResourceRelationships/resource': 'getAllResource',
  'post&/api/ResourceRelationships/resource/single': 'getResource',
  //23-5-4
  'post&/api/ResourceRelationships/resource/details': 'getResourceDetails',
  'post&/api/ResourceRelationships': 'deleteResourceRelationships',
  'put&/api/ResourceRelationships/resource': 'updateMainLinkResource',
  'post&/api/ResourceRelationships/main/details': 'batchGetMainDetails',
};

const dcsBiz = {
  'get&/api/Businesses': 'getBusinesses',
  'get&/api/CheckRule/Search': 'searchCheckRule',
  'get&/api/CheckRule/{resourceId}/CheckRuleRelationMetadata': 'getCheckRuleRelatedMetadata',
  'post&/api/CheckRule': 'addCheckRule',
  'put&/api/CheckRule/{resourceId}': 'editCheckRule',
  'delete&/api/CheckRule/{resourceId}': 'deleteCheckRule',
  'get&/api/CheckRuleType': 'getCheckRuleType',
  'get&/api/CheckTaskInfo/Search': 'getCheckTaskInfo',
  'get&/api/CheckTaskInfo/{id}/Detail': 'getCheckTaskInfoById',
  'put&/api/CheckTaskInfo/SingleExecution': 'runCheckTask',
  'get&/api/CheckTaskInfo/{id}/CheckTaskExecuteRecord/Search': 'searchCheckTaskInfo',
  'get&/api/CheckTaskInfo/CheckTaskExecuteRecord/{id}': 'getCheckTaskExecuteRecordById',
  'get&/api/CheckTaskInfo/CheckTaskExecuteRecord/Search': 'getCheckTaskExecuteRecord',
  'get&/api/CheckTaskInfo/CheckTaskExecuteRecord/{id}/Errors': 'getCheckTaskExecuteRecordErrors',
  'get&/api/DataSource': 'getDataSource',
  'post&/api/DataSource': 'addDataSource',
  'put&/api/DataSource/{resourceId}': 'editDataSource',
  'delete&/api/DataSource/{resourceId}': 'deleteDataSource',
  'get&/api/DataSource/{resourceId}/DbInfos': 'getDbInfosByResourceId',
  'post&/api/DataSource/{resourceId}/DbInfos': 'searchMetadataInfoByResourceId',
  'get&/api/Departments': 'getDepartments',
  'get&/api/Districts': 'getDistricts',
  'get&/api/Domains': 'getDomains',
  'get&/api/Export/ExportDataRequestCategory': 'exportDataRequestCategory',
  'get&/api/KettleJobs': 'getKettleJobs',
  'post&/api/KettleJobs': 'addKettleJobs',
  'put&/api/KettleJobs/{resourceId}': 'editKettleJobs',
  'delete&/api/KettleJobs/{resourceId}': 'deleteKettleJobs',
  'get&/api/KettleJobs/Search': 'searchKettleJobs',
  'get&/api/KettleJobs/{id}': 'getKettleJobById',
  'get&/api/KettleJobs/{id}/Records': 'getKettleJobRecords',
  'get&/api/KettleJobs/Records/Search': 'getKettleJobRecordsByMetadataId',
  'get&/api/KettleJobs/Tags': 'getTags',
  'post&/api/KettleJobs/Import': 'importKettleJobs',
  'post&/api/KettleJobs/Export': 'exportKettleJobs',
  'put&/api/KettleJobs/{id}/Run': 'runJobs',
  'put&/api/KettleJobs/{id}/Stop': 'stopJobs',
  'put&/api/KettleJobs/SingleExecution': 'singleExecJobs',
  'get&/api/KettleJobs/{id}/Records/Export': 'exportTop10Jobs',
  'get&/api/KettleJobs/Records/{id}/Export': 'exportETLJobRecords',
  'get&/api/Metadata/{id}': 'getMetadataById',
  'put&/api/Metadata/{id}': 'editMetadata',
  'delete&/api/Metadata/{id}': 'deleteMetadata',
  'get&/api/Metadata/dockInfo': 'getMetadataDockInfo',
  'get&/api/Metadata': 'getMetadata',
  'post&/api/Metadata': 'addMetadata',
  'post&/api/Metadata/FindPageBySearch': 'searchMetadata',
  'post&/api/Metadata/UpdateMetadataCountInfo': 'updateMetadataCountInfo',
  'get&/api/ResourceDb/tree': 'getResourceDbTree',
  'get&/api/ResourceDb': 'getResourceDb',
  'post&/api/ResourceDb': 'addResourceDb',
  'get&/api/ResourceDb/{id}': 'getResourceDbById',
  'put&/api/ResourceDb/{id}': 'editResourceDb',
  'delete&/api/ResourceDb/{id}': 'deleteResourceDb',
  'post&/api/ResourceDb/Batch': 'batchAddResourceDb',
  'get&/api/ResourceDb/{id}/Metadata': 'getMetadataByResourceDb',
  'post&/api/ResourceDb/{id}/ExternalResource/Search': 'searchExternalResource',
  'get&/api/ResourceDb/{id}/ExternalResource/Statistic': 'getExternalResourceAmount',
  'post&/api/ResourceDb/{id}/ExternalResource': 'addExternalResource',
  'put&/api/ResourceDb/{id}/ExternalResource': 'editExternalResource',
  'delete&/api/ResourceDb/{id}/ExternalResource': 'deleteExternalResource',
  'delete&/api/ResourceDb/{id}/ExternalResource/Batch': 'batchDeleteExternalResource',
  'get&/api/Services': 'getServices',
  'get&/api/Statistics/Metadata/ThirtyEtlJobWriteCount': 'getThirtyEtlJobWriteCount',
  'get&/api/Statistics/CheckTaskExecuteRecord/LastThirtyTimesRecord': 'getLastThirtyTimesRecord',
  'get&/api/Statistics/CheckTaskExecuteRecord/LastThirtyTimesRaise': 'getLastThirtyTimesRaise',
  'get&/api/Statistics/Metadata/Count': 'getMetadataCount',
  'get&/api/Statistics/CheckRule/Count': 'getCheckRuleCount',
  'get&/api/Statistics/Metadata/Activity': 'getMetadataActivity',
  'get&/api/Tags': 'getTags',
  'get&/api/Themes': 'getThemes',
  'post&/api/Departments': 'addDepartments',
  'get&/api/Departments/{id}': 'getDepartmentById',
  'put&/api/Departments/{id}': 'editDepartment',
  'delete&/api/Departments/{id}': 'deleteDepartment',
  'post&/api/Departments/batch': 'getDepartmentsByIds',
  'post&/api/Departments/import': 'importDepartments',
  'post&/api/Domains': 'addDomain',
  'get&/api/Domains/{id}': 'getDomainById',
  'put&/api/Domains/{id}': 'editDomain',
  'delete&/api/Domains/{id}': 'deleteDomain',
  'post&/api/Domains/batch': 'getDomainsByIds',
  'post&/api/Domains/import': 'importDomains',
  'get&/api/Projects': 'getProjects',
  'post&/api/Projects': 'addProject',
  'get&/api/Projects/{id}': 'getProjectById',
  'put&/api/Projects/{id}': 'editProject',
  'delete&/api/Projects/{id}': 'deleteProject',
  'get&/api/Projects/{id}/detail': 'getProjectDetailById',
  'post&/api/Projects/import': 'importProjects',
  'post&/api/ResourceDb/search/batch': 'getResourceDbsByIds',
  'post&/api/ResourceDb/import': 'importResourceDbs',
  'post&/api/Themes': 'addTheme',
  'get&/api/Themes/{id}': 'getThemeById',
  'put&/api/Themes/{id}': 'editTheme',
  'delete&/api/Themes/{id}': 'deleteTheme',
  'post&/api/Projects/{id}/defaultResourceDbs':'addResourceDbsByProjectId',
};

module.exports = {
  gcsBiz,
  cgsBiz,
  mmtBiz,
  aggsBiz,
  authBiz,
  edmsBiz,
  orgsBiz,
  eventBiz,
  viscsBiz,
  alarmBiz,
  quartzBiz,
  geoDataBiz,
  resourceBiz,
  boundaryBiz,
  facilityBiz,
  fileStorageBiz,
  geoAnalysisBiz,
  preplanAnalysisBiz,
  modelAnalysisBiz,
  videoFusionServiceBiz,
  auditBiz,
  vcsBiz,
  assetBiz,
  alertsPlatformBiz,
  dasBiz,
  scheduleBiz,
  rrsBiz,
  dcsBiz,
};
